version: '3'
services:
  db:
    image: postgres:15.1
    environment:
      PGDATA: /var/lib/postgresql/local_data
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/postgresql:/var/lib/postgresql
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      target: development
    environment:
      PYTHONUNBUFFERED: "1"
      FLASK_DEBUG: "1"
    volumes:
      - ./backend:/home/docker_user/src
    ports:
      - "5000:5000"
    depends_on:
      - db
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
