version: '3'
services:
{% if cookiecutter.setup_postgres_database == 'y' %}
  postgres:
    image: postgres:15.1
    environment:
      PGDATA: /var/lib/postgresql/local_data
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/postgresql:/var/lib/postgresql{% endif %}
{% if cookiecutter.setup_mongo_database == 'y' %}
  mongo:
    image: mongo:6.0-jammy
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/mongodb:/data/db{% endif %}
  {{cookiecutter.backend_app_name}}:
    restart: "no"
    build:
      context: ./{{cookiecutter.backend_app_name}}
      target: development
    environment:
      PYTHONUNBUFFERED: "1"
      FLASK_DEBUG: "1"
    volumes:
      - ./{{cookiecutter.backend_app_name}}:/home/docker_user/src
{% if cookiecutter.setup_postgres_database == 'y' or cookiecutter.setup_mongo_database == 'y' %}
    depends_on:
      {% if cookiecutter.setup_postgres_database == 'y' %}- postgres{% endif %}
      {% if cookiecutter.setup_mongo_database == 'y' %}- mongo{% endif %}{% endif %}
  {{cookiecutter.frontend_app_name}}:
    restart: "no"
    build:
      context: ./{{cookiecutter.frontend_app_name}}
      target: development
    volumes:
      - /home/node/src/node_modules
      - ./{{cookiecutter.frontend_app_name}}:/home/node/src
    depends_on:
      - {{cookiecutter.backend_app_name}}
  nginx:
    restart: "no"
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - {{cookiecutter.backend_app_name}}
      - {{cookiecutter.frontend_app_name}}
